name: Website Deploy

on:
  push:
    branches:
      - develop
      - github-actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true

    - name: Install dependencies
      run: |
        sudo apt install hunspell libhunspell-dev hunspell-en-us

    - name: Build site
      run: |
        bundle exec rake
        bundle exec rake spell_check

    - name: Deploy site
      run: |
        export GPG_TTY=$(tty)
        gpg --passphrase ${{ secrets.GPG_PASSPHRASE }} --output /tmp/dual_deploy_key --decrypt dual_deploy_key.enc
        eval "$(ssh-agent -s)"
        chmod 600 /tmp/dual_deploy_key
        bash _scripts/deploy.sh
